[package]
name = "hello_world"
version = "0.0.0"
edition = "2021"
authors = [
  "ramumsrk02071981@gmail.com",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"
